import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {styled } from 'linaria/react'
import React from 'react'
const StyledHeading=styled.h1`
color:blue;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledHeading>Hello next</StyledHeading>
    </div>
  )
}
